<?php
/**
 * @copyright Copyright (c) 2024 Aurora Creation Sp. z o.o. (http://auroracreation.com)
 */
use Aurora\Santander\ViewModel\Order;
use Aurora\Santander\ViewModel\Rates;
use Aurora\Santander\Block\Form\Santander;

/** @var Santander $block */
/** @var Order $orderModel */
/** @var Rates $ratesModel */

$orderModel = $block->getOrder();
$ratesModel = $block->getRates();
$order = $orderModel->getLastOrder();
$billingAddress = $order->getBillingAddress();
$totalValue = 0;
$totalQty = 0;
$count = 0;
$currencyCode = $order->getOrderCurrencyCode();
// phpcs:disable Generic.Files.LineLength.TooLong

?>

<?php
if (!$order->getId()) {
    return;
}
?>

<form id="eraty-form" name="formularz_eRaty" action="https://wniosek.eraty.pl/formularz/" method="post">
    <?php foreach ($order->getAllItems() as $key => $item): ?>
        <?php
        if (!$block->validateItem($item)) {
            continue;
        }
        ?>

        <?php
        $qty = $item->getQtyOrdered();
        $discount = $item->getDiscountAmount() ?? 0;
        $price = $block->calculateItemPrice($item);
        $displayPrice = $orderModel->getPricePLN($price, $currencyCode);
        ?>

        <?php
        $count++;
        $totalValue += $price;
        $totalQty += $qty;
        ?>

        <input name="idTowaru<?= /* @noEscape */ $count ?>" readonly="readonly"
               type="hidden" value="<?= /* @noEscape */ $item->getProductId() ?>"/>
        <input name="nazwaTowaru<?= /* @noEscape */ $count ?>" readonly="readonly"
               type="hidden" value="<?= /* @noEscape */ $item->getName() ?>"/>
        <input name="wartoscTowaru<?= /* @noEscape */ $count ?>" readonly="readonly"
               type="hidden" value="<?= /* @noEscape */ $displayPrice ?>"/>
        <input name="liczbaSztukTowaru<?=  /* @noEscape */$count ?>" readonly="readonly"
               type="hidden" value="<?= /* @noEscape */ (int)$qty ?>"/>
        <input name="jednostkaTowaru<?= /* @noEscape */ $count ?>" readonly="readonly" type="hidden" value="szt."/>
    <?php endforeach; ?>

    <?php if ($order->getShippingInclTax() > 0): ?>
        <?php
        $totalValue += $order->getShippingInclTax();
        $totalQty++;
        $count++;
        ?>
        <input name="idTowaru<?= /* @noEscape */ $count ?>" readonly="readonly" type="hidden" value="KosztPrzesylki">
        <input name="nazwaTowaru<?= /* @noEscape */ $count ?>" readonly="readonly" type="hidden" value="Koszt Przesyłki">
        <input name="wartoscTowaru<?= /* @noEscape */ $count ?>"
               readonly="readonly"
               type="hidden"
               value="<?= /* @noEscape */  $orderModel->getPricePLN($order->getShippingInclTax(), $currencyCode) ?>"
        />
        <input name="liczbaSztukTowaru<?= /* @noEscape */ $count ?>" readonly="readonly" type="hidden" value="1">
        <input name="jednostkaTowaru<?= /* @noEscape */ $count ?>" readonly="readonly" type="hidden" value="sztuki">
    <?php endif ?>

    <input type="hidden" name="wartoscTowarow" value="<?= /* @noEscape */  $orderModel->getPricePLN($totalValue, $currencyCode) ?>">
    <input type="hidden" name="liczbaSztukTowarow" value="<?= /* @noEscape */  $totalQty ?>">
    <input type="hidden" name="numerSklepu" value="<?= /* @noEscape */  $ratesModel->getShopId($order->getAllItems()) ?>">
    <input type="hidden" name="typProduktu" value="0">
    <input type="hidden" name="sposobDostarczeniaTowaru" value="<?= /* @noEscape */  $order->getShippingDescription() ?>">
    <input type="hidden" name="nrZamowieniaSklep" value="<?= /* @noEscape */  $order->getIncrementId() ?>">
    <input type="hidden" name="imie" value="<?= /* @noEscape */  $billingAddress->getFirstname() ?>">
    <input type="hidden" name="nazwisko" value="<?= /* @noEscape */  $billingAddress->getLastname() ?>">
    <input type="hidden" name="email" value="<?= /* @noEscape */  $billingAddress->getEmail() ?>">
    <input type="hidden" name="telKontakt" value="<?= /* @noEscape */  $billingAddress->getTelephone() ?>">
    <input type="hidden" name="ulica" value="<?= /* @noEscape */  implode(' ', $billingAddress->getStreet()) ?>">
    <input type="hidden" name="miasto" value="<?= /* @noEscape */  $billingAddress->getCity() ?>">
    <input type="hidden" name="kodPocz" value="<?= /* @noEscape */ $billingAddress->getPostcode() ?>">
    <input type="hidden" name="char" value="UTF">
    <input type="hidden" name="wniosekZapisany"
           value="<?= /* @noEscape */  $orderModel->getSaveOrderPageUrl([
               'order' => $order->getId(),
               'wniosek' => 'przyjety',
           ]) ?>id_zamowienia/"
    />
    <input type="hidden" name="wniosekAnulowany"
           value="<?= /* @noEscape */  $orderModel->getSaveOrderPageUrl([
               'order' => $order->getId(),
               'wniosek' => 'odrzucony',
           ]) ?>id_zamowienia/"
    />
</form>

<script>
    window.addEventListener('load', function () {
        document.getElementById('eraty-form').submit();
    });
</script>
