<?php
/**
 * @copyright Copyright (c) 2024 Aurora Creation Sp. z o.o. (http://auroracreation.com)
 */
use Magento\Framework\Escaper;

/** @var Escaper $escaper */

$installment = $block->getInstallment();
$rates = $block->getRates();
$product = $installment->getProduct();
$installment->calculateInstallment($product);

// phpcs:disable Generic.Files.LineLength.TooLong
?>

<?php if ($installment->isAvailable() && $product->getStatus() != 2 && $installment->qty !== null && $installment->percent !== null): ?>
    <div>
        <a onclick="calcInstallment()"
            title="<?= $escaper->escapeHtml(__('Calculate installment!')); ?>"
            style="cursor: pointer;">
            <img src="<?= $escaper->escapeUrl($block->getViewFileUrl('Aurora_Santander::images/oblicz_raty.png')) ?>"
                alt="<?= $escaper->escapeHtml(__('Calculate installment!')); ?>">
        </a>
    </div>

<script>

    window.santanderPrice = <?= $escaper->escapeHtml($installment->toPLN($installment->price)) ?>;

    function calcInstallment()
    {
        window.open(
            "https://wniosek.eraty.pl/symulator/oblicz/numerSklepu/<?= $escaper->escapeUrl($rates->getShopId([$installment])) ?>/typProduktu/0/wartoscTowarow/" + window.santanderPrice,
            "Policz_rate",
            "width=640,height=500,directories=no,location=no,menubar=no,resizable=yes,scrollbars=yes,status=no,toolbar=no"
        );
    }
</script>

<?php endif; ?>
