<?php
/**
 * @copyright Copyright (c) 2020 Aurora Creation Sp. z o.o. (https://auroracreation.com)
 */

$installment = $block->getInstallment();
$rates = $block->getRates();
$product = $installment->getProduct();
$installment->calculateInstallment($product);
?>

<?php if ($installment->isAvailable() && $product->getStatus() != 2 && $installment->qty !== null && $installment->percent !== null): ?>
    <div>
        <a onclick='window.open("https://wniosek.eraty.pl/symulator/oblicz/numerSklepu/<?= $rates->getShopId([$installment]); ?>/typProduktu/0/wartoscTowarow/<?= $installment->toPLN($installment->price); ?>", "Policz_rate", "width=640,height=500,directories=no,location=no,menubar=no,resizable=yes,scrollbars=yes,status=no,toolbar=no");'
            title="<?= $block->escapeHtml(__('Calculate installment!')); ?>" style="cursor: pointer;">
            <img src="<?= $this->getViewFileUrl('Aurora_Santander::images/oblicz_raty.png') ?>"
                alt="<?= $block->escapeHtml(__('Calculate installment!')); ?>">
        </a>
    </div>
<?php endif; ?>
