<?php
/**
 * @copyright Copyright (c) 2020 Aurora Creation Sp. z o.o. (https://auroracreation.com)
 */
?>

<div class="block_content">
    <?php if ($block->getLpLink() && $block->getIsBanner()): ?>
        <a title="<?= $block->escapeHtml(__('See how to buy in installments')); ?>" href="<?= $block->getLpUrl(); ?>" target="_blank">
            <img 
                src="<?= $this->getViewFileUrl('Aurora_Santander::images/banner_eraty.jpg') ?>" 
                alt="<?= $block->escapeHtml(__('See how to buy in installments')); ?>">
        </a>
    <?php elseif (!$block->getLpLink() && $block->getIsBanner()): ?>
        <img 
            src="<?= $this->getViewFileUrl('Aurora_Santander::images/banner_eraty.jpg') ?>" 
            alt="<?= $block->escapeHtml(__('See how to buy in installments')); ?>">
    <?php elseif ($block->getLpLink() && !$block->getIsBanner()): ?> 
        <a href="<?= $block->getLpUrl(); ?>" target="_blank">
           <?= __('How to buy with eRata?'); ?> 
        </a>
    <?php endif; ?>
</div>
