<?php
/**
 * @copyright Copyright (c) 2024 Aurora Creation Sp. z o.o. (http://auroracreation.com)
 */

use Aurora\Santander\Block\Form\Santander;
use Magento\Framework\Escaper;

/** @var Escaper $escaper */
?>

<?php
/**
 * @var Santander $block;
 */
?>

<?php
$instructions = $block->getInstructions();

if (!$instructions) {
    return;
}

$code = $block->getMethodCode();
?>

<div class="items <?= $escaper->escapeHtml($code) ?> instructions agreement checkout-agreement-item-content"
     id="payment_form_<?= $escaper->escapeHtml($code) ?>"
     style="display: none;">
    <?= /* @noEscape */ nl2br($escaper->escapeHtml($instructions)) ?>
</div>
